'use strict';
const $ = s => document.querySelector(s);
const games = [
 {id:'slope',name:'Neon Slope',art:'NEON<br>SLOPE',category:'Arcade',color:'#b7ff39',symbol:'◉',tag:'DOWNHILL CHAOS',desc:'Stay on the track. Dodge the blocks. Send it.',controls:'← → or A / D to steer. Touch: hold the arrow buttons.',note:'An original Slope-inspired mini-game, not the official Slope.'},
 {id:'snake',name:'Snake Syndicate',art:'SNAKE<br>SYNDICATE',category:'Classic',color:'#b59aff',symbol:'▟',tag:'CERTIFIED CLASSIC',desc:'Eat. Grow. Try not to eat yourself.',controls:'Arrow keys or W A S D to turn. Touch: use the direction buttons.'},
 {id:'breakout',name:'Brick Riot',art:'BRICK<br>RIOT',category:'Classic',color:'#ff9566',symbol:'▦',tag:'SMASH EVERYTHING',desc:'One paddle. One ball. Absolutely no mercy.',controls:'← → / A D or move the pointer to control the paddle.'},
 {id:'flap',name:'Flappy Lads',art:'FLAPPY<br>LADS',category:'Arcade',color:'#83dce9',symbol:'↗',tag:'JUST ONE MORE TRY',desc:'The lads have wings. This can only end well.',controls:'Space, ↑, tap the game or press ACTION to flap.'},
 {id:'dodge',name:'Meteor Meltdown',art:'METEOR<br>MELTDOWN',category:'Arcade',color:'#ff83c4',symbol:'✳',tag:'SURVIVAL MODE',desc:'Dodge the sky. Keep the streak alive.',controls:'← → / A D or move the pointer to dodge. Touch: hold arrows.'},
 {id:'crossy',name:'Crossy Lads',art:'CROSSY<br>LADS',category:'Arcade',color:'#8be04e',symbol:'🐔',tag:'WHY DID CALUM CROSS?',desc:'Roads, rivers, trains, coins and one hungry eagle. Frazer is driving.',controls:'Swipe on the game (or use arrow keys / W A S D) to hop. Tap to hop forward. Ride the logs, grab coins, keep moving or the eagle gets you.',note:'A Crossy Road-inspired mini-game, not the official Crossy Road.'},
 {id:'reaction',name:'Reflex Check',art:'REFLEX<br>CHECK',category:'Quick',color:'#f1ed85',symbol:'ϟ',tag:'ARE YOU LOCKED IN?',desc:'Wait for green. Tap fast. Prove you’re awake.',controls:'Wait for green, then click the game or press Space / ACTION.',note:'Lower scores are better. Reaction time is measured in milliseconds.'}
];
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Private mode can disable storage. */}}
let favourites=read('bunker:favourites',[]);if(!Array.isArray(favourites))favourites=[];
let category='All';
function renderCards(){const query=$('#search').value.trim().toLowerCase();const list=games.filter(g=>(category==='All'||(category==='Favourites'?favourites.includes(g.id):g.category===category))&&`${g.name} ${g.desc} ${g.category}`.toLowerCase().includes(query));$('#game-grid').innerHTML=list.map((g,i)=>`<article class="game-card" style="--card-color:${g.color}"><button class="card-art" data-play="${g.id}" aria-label="Play ${g.name}"><span class="art-title">${g.art}</span><span class="art-symbol" aria-hidden="true">${g.symbol}</span><img class="art-photo" src="/images/${games.indexOf(g)%2?'el-classico':'hammock'}.jpeg" alt="" loading="lazy"><span class="card-badge">${g.tag}</span></button><button class="favourite" data-favourite="${g.id}" aria-label="Favourite ${g.name}" aria-pressed="${favourites.includes(g.id)}">${favourites.includes(g.id)?'♥':'♡'}</button><div class="card-body"><h3>${g.name}</h3><p>${g.desc}</p><div class="card-bottom"><span>${g.category.toUpperCase()} · FREE</span><button class="play" data-play="${g.id}">PLAY NOW ↗</button></div></div></article>`).join('');$('#result-count').textContent=`${list.length} GAMES. ZERO EXCUSES.`;$('#empty').hidden=!!list.length}
$('#search').addEventListener('input',renderCards);
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});renderCards()}));
$('#game-grid').addEventListener('click',e=>{const play=e.target.closest('[data-play]');if(play)openGame(play.dataset.play);const fav=e.target.closest('[data-favourite]');if(fav){const id=fav.dataset.favourite;favourites=favourites.includes(id)?favourites.filter(x=>x!==id):[...favourites,id];write('bunker:favourites',favourites);renderCards()}});
['#random-top','#random-hero','#random-bottom'].forEach(s=>$(s).addEventListener('click',()=>openGame(games[Math.floor(Math.random()*games.length)].id)));
const face=new Image();face.src='/images/hammock.jpeg';
const calumImg=new Image();calumImg.src='/images/calum-face.jpg';
const frazerCar=new Image();frazerCar.src='/images/frazer-car.jpg';
const dialog=$('#player'),canvas=$('#canvas'),ctx=canvas.getContext('2d'),W=900,H=500,dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=W*dpr;canvas.height=H*dpr;ctx.scale(dpr,dpr);ctx.imageSmoothingQuality='high';
let current=null,state=null,running=false,paused=false,score=0,best=0,frame=0,last=0,keys=new Set(),opener=null;
function bestKey(){return `bunker:best:${current.id}`}
function updateScore(n){score=Math.max(0,Math.floor(n));$('#score').textContent=current.id==='reaction'?`${score} ms`:score}
function setOverlay(title,msg,label){$('#overlay-title').textContent=title;$('#overlay-message').textContent=msg;$('#start').textContent=label;$('#overlay').hidden=false}
function openGame(id){opener=document.activeElement;current=games.find(g=>g.id===id);cancelAnimationFrame(frame);running=false;paused=false;keys.clear();$('#pause').textContent='PAUSE';$('#game-title').textContent=current.name;$('#instructions').textContent=current.controls;$('#game-note').textContent=current.note||'Original Bunker Box mini-game. Your best score stays on this device.';best=Number(read(bestKey(),0))||0;$('#best').textContent=best?`${best}${id==='reaction'?' ms':''}`:'—';updateScore(0);state=initialState(id);draw();setOverlay('READY TO SEND IT?',current.controls,'LET’S GO →');if(!dialog.open)dialog.showModal()}
function initialState(id){if(id==='slope')return {x:0,t:0,obstacles:[],spawn:0};if(id==='snake')return {body:[{x:10,y:10},{x:9,y:10},{x:8,y:10}],dx:1,dy:0,nextX:1,nextY:0,food:{x:20,y:10},tick:0};if(id==='breakout')return {paddle:450,x:450,y:365,vx:230,vy:-290,bricks:Array.from({length:40},(_,i)=>({x:42+(i%10)*82,y:45+Math.floor(i/10)*35,alive:true})),lives:3};if(id==='flap')return {y:230,vy:0,pipes:[],spawn:0};if(id==='dodge')return {x:450,t:0,rocks:[],spawn:0};if(id==='crossy')return crossyInit();return {wait:1.7+Math.random()*3,t:0,green:false,started:0}}
function start(){if(paused){paused=false;$('#pause').textContent='PAUSE';$('#overlay').hidden=true;last=performance.now();frame=requestAnimationFrame(loop);canvas.focus();return}state=initialState(current.id);updateScore(0);running=true;paused=false;keys.clear();$('#pause').textContent='PAUSE';$('#overlay').hidden=true;cancelAnimationFrame(frame);last=performance.now();frame=requestAnimationFrame(loop);canvas.focus()}
function finish(message,won=false){running=false;cancelAnimationFrame(frame);keys.clear();if(score>0&&(!best||(current.id==='reaction'?score<best:score>best))){best=score;write(bestKey(),best);$('#best').textContent=`${best}${current.id==='reaction'?' ms':''}`;message+=' New personal best!'}setOverlay(won?'ABSOLUTE SCENES.':'ONE MORE GO?',message,'PLAY AGAIN ↻')}
function togglePause(){if(!running)return;if(current.id==='reaction'){running=false;cancelAnimationFrame(frame);setOverlay('ROUND RESET','Reaction rounds restart when paused.','START AGAIN →');return}paused=!paused;keys.clear();$('#pause').textContent=paused?'RESUME':'PAUSE';if(paused){cancelAnimationFrame(frame);setOverlay('TAKE A BREATHER.','Your game is paused.','RESUME →')}else{$('#overlay').hidden=true;last=performance.now();frame=requestAnimationFrame(loop);canvas.focus()}}
function closeGame(){running=false;cancelAnimationFrame(frame);keys.clear();dialog.close();opener?.focus()}
$('#close').addEventListener('click',closeGame);dialog.addEventListener('cancel',e=>{e.preventDefault();closeGame()});dialog.addEventListener('close',()=>{running=false;cancelAnimationFrame(frame);keys.clear()});$('#start').addEventListener('click',start);$('#restart').addEventListener('click',()=>{paused=false;start()});$('#pause').addEventListener('click',togglePause);
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(dialog.requestFullscreen)await dialog.requestFullscreen();else $('#game-note').textContent='Fullscreen is not available in this browser. Rotate your phone for a wider view.'}catch{$('#game-note').textContent='Fullscreen is not available in this browser.'}});
function action(key){if(!running||paused)return;if(current.id==='snake'){const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[key];if(d&&(d[0]!==-state.dx||d[1]!==-state.dy)){state.nextX=d[0];state.nextY=d[1]}}if(current.id==='flap'&&(key==='Space'||key==='ArrowUp'))state.vy=-320;if(current.id==='crossy')crossyHop(key);if(current.id==='reaction'&&key==='Space'){if(!state.green){updateScore(0);finish('Too early! Wait until the screen turns green.')}else{updateScore(performance.now()-state.started);finish(`${score} ms. That’s your reaction time.`,true)}}}
function normalize(e){return {KeyA:'ArrowLeft',KeyD:'ArrowRight',KeyW:'ArrowUp',KeyS:'ArrowDown'}[e.code]||e.code}
document.addEventListener('keydown',e=>{if(!dialog.open){if(e.key==='/'&&e.target.tagName!=='INPUT'){e.preventDefault();$('#search').focus()}return}const key=normalize(e);if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(key)&&e.target===canvas){e.preventDefault();keys.add(key);if(!e.repeat)action(key)}if(e.code==='KeyP'&&e.target===canvas)togglePause()});document.addEventListener('keyup',e=>keys.delete(normalize(e)));
window.addEventListener('blur',()=>{keys.clear();if(running&&!paused)togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)togglePause()});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);action(b.dataset.key)});['pointerup','pointercancel','lostpointercapture'].forEach(type=>b.addEventListener(type,()=>keys.delete(b.dataset.key)))});
let swipe=null;canvas.addEventListener('pointerdown',e=>{canvas.focus();if(current&&current.id==='crossy'){swipe={x:e.clientX,y:e.clientY,id:e.pointerId};return}action('Space');movePointer(e)});
canvas.addEventListener('pointerup',e=>{if(!swipe||swipe.id!==e.pointerId)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;swipe=null;if(Math.hypot(dx,dy)<24)return action('Space');action(Math.abs(dx)>Math.abs(dy)?(dx>0?'ArrowRight':'ArrowLeft'):(dy>0?'ArrowDown':'ArrowUp'))});canvas.addEventListener('pointercancel',()=>{swipe=null});canvas.addEventListener('pointermove',movePointer);
function movePointer(e){if(!running||paused)return;const x=(e.clientX-canvas.getBoundingClientRect().left)/canvas.getBoundingClientRect().width*W;if(current.id==='breakout')state.paddle=Math.max(60,Math.min(W-60,x));if(current.id==='dodge')state.x=Math.max(22,Math.min(W-22,x))}
function loop(now){if(!running||paused)return;const dt=Math.min((now-last)/1000,.04);last=now;update(dt);draw();if(running)frame=requestAnimationFrame(loop)}
function update(dt){const steer=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0);const s=state;
if(current.id==='slope'){s.t+=dt;s.x+=steer*dt*1.6;s.spawn-=dt;const speed=1+s.t*.012;if(s.spawn<=0){s.obstacles.push({x:(Math.random()-.5)*1.4,z:0});s.spawn=.7+Math.random()*.6}for(const o of s.obstacles)o.z+=dt*.43*speed;s.obstacles=s.obstacles.filter(o=>o.z<1.1);updateScore(s.t*10);if(Math.abs(s.x)>.93)return finish('You fell off the track. Steer a little earlier!');if(s.obstacles.some(o=>o.z>.88&&o.z<1.04&&Math.abs(o.x-s.x)<.18))return finish(`Block collision. You made it ${score} metres.`)}
if(current.id==='snake'){s.tick+=dt;if(s.tick>=Math.max(.075,.15-score*.002)){s.tick=0;s.dx=s.nextX;s.dy=s.nextY;const head={x:s.body[0].x+s.dx,y:s.body[0].y+s.dy};const eating=head.x===s.food.x&&head.y===s.food.y;const body=eating?s.body:s.body.slice(0,-1);if(head.x<0||head.x>=30||head.y<0||head.y>=16||body.some(p=>p.x===head.x&&p.y===head.y))return finish(`Snake stopped. ${score} snacks collected.`);s.body.unshift(head);if(eating){updateScore(score+1);const free=[];for(let y=0;y<16;y++)for(let x=0;x<30;x++)if(!s.body.some(p=>p.x===x&&p.y===y))free.push({x,y});if(!free.length)return finish('You filled the board!',true);s.food=free[Math.floor(Math.random()*free.length)]}else s.body.pop()}}
if(current.id==='breakout'){s.paddle=Math.max(60,Math.min(W-60,s.paddle+steer*dt*620));const prevY=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.x<10||s.x>W-10){s.vx*=-1;s.x=Math.max(10,Math.min(W-10,s.x))}if(s.y<10){s.vy=Math.abs(s.vy);s.y=10}if(s.vy>0&&prevY<=435&&s.y>=435&&Math.abs(s.x-s.paddle)<70){s.y=435;s.vy=-Math.abs(s.vy);s.vx=(s.x-s.paddle)*6}for(const b of s.bricks){if(b.alive&&s.x>b.x-8&&s.x<b.x+80&&s.y>b.y-8&&s.y<b.y+32){b.alive=false;s.vy*=-1;updateScore(score+10);break}}if(s.y>H+10){s.lives--;if(!s.lives)return finish(`Out of balls. ${score} points of brick destruction.`);s.x=s.paddle;s.y=365;s.vx=230;s.vy=-290}if(s.bricks.every(b=>!b.alive))return finish('All bricks cleared. Total demolition.',true)}
if(current.id==='flap'){s.vy+=dt*850;s.y+=s.vy*dt;s.spawn-=dt;if(s.spawn<=0){s.pipes.push({x:W+30,gap:130+Math.random()*240,passed:false});s.spawn=1.8}for(const p of s.pipes){p.x-=dt*220;if(p.x+65<180&&!p.passed){p.passed=true;updateScore(score+1)}if(p.x<205&&p.x+65>155&&(s.y-21<p.gap-90||s.y+21>p.gap+90))return finish(`${score} gates cleared. The lads will fly again.`)}s.pipes=s.pipes.filter(p=>p.x>-80);if(s.y<22||s.y>H-22)return finish('Gravity wins this round.')}
if(current.id==='dodge'){s.t+=dt;s.x=Math.max(22,Math.min(W-22,s.x+steer*dt*500));s.spawn-=dt;if(s.spawn<=0){s.rocks.push({x:25+Math.random()*850,y:-40,r:15+Math.random()*15,speed:170+Math.random()*130+s.t*5});s.spawn=Math.max(.16,.55-s.t*.006)}for(const r of s.rocks){r.y+=dt*r.speed;if(Math.hypot(r.x-s.x,r.y-445)<r.r+18)return finish(`You survived ${score} seconds of meteor madness.`)}s.rocks=s.rocks.filter(r=>r.y<550);updateScore(s.t)}
if(current.id==='crossy')return crossyUpdate(dt);
if(current.id==='reaction'){s.t+=dt;if(!s.green&&s.t>=s.wait){s.green=true;s.started=performance.now()}}
}
const CT=75,CC=12;
function crossyInit(){return {px:5,py:0,cam:-1,t:0,hop:0,idle:0,maxRow:0,coins:0,lanes:{},eagle:null}}
function crossyLane(r){const s=state;if(s.lanes[r])return s.lanes[r];const prev=s.lanes[r-1];let l;
 if(r<=1)l={type:'grass',trees:r===1?[0,11]:[],coins:[]};
 else{const roll=Math.random(),runOk=t=>!(prev&&prev.type===t&&prev.run>=(t==='road'?4:t==='water'?3:2));let type;
  if(r===3)type='water';else if(r>5&&roll<.12&&runOk('rail'))type='rail';else if(roll<.34&&runOk('water')&&r>2)type='water';else if(roll<.65&&runOk('road'))type='road';else type='grass';
  const run=prev&&prev.type===type?prev.run+1:1,dir=prev&&prev.type===type?-prev.dir:(Math.random()<.5?1:-1),level=Math.min(r,150);
  if(type==='grass'){const trees=[],coins=[];for(let c=0;c<CC;c++){if(Math.random()<.2)trees.push(c);else if(Math.random()<.07)coins.push(c)}l={type,trees,coins}}
  if(type==='road'){const n=2+Math.floor(Math.random()*2),gap=(W+220)/n,off=Math.random()*gap,coins=Math.random()<.35?[Math.floor(Math.random()*CC)]:[];l={type,run,dir,coins,speed:95+Math.random()*80+level*1.3,cars:Array.from({length:n},(_,i)=>({x:off+i*gap-150}))}}
  if(type==='water'){const n=3,gap=(W+360)/n,off=Math.random()*gap;l={type,run,dir,coins:[],speed:55+Math.random()*50+level*.5,logs:Array.from({length:n},(_,i)=>({x:off+i*gap-200,w:CT*(2+Math.floor(Math.random()*2))}))}}
  if(type==='rail')l={type,run,dir,coins:[],timer:1.5+Math.random()*4,train:null}}
 return s.lanes[r]=l}
function crossyHop(key){const s=state;if(s.eagle)return;const d={ArrowUp:[0,1],Space:[0,1],ArrowDown:[0,-1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[key];if(!d)return;
 const nx=Math.round(s.px)+d[0],ny=s.py+d[1];if(nx<0||nx>=CC||ny<Math.ceil(s.cam-.4))return;const l=crossyLane(ny);if(l.type==='grass'&&l.trees.includes(nx))return;
 s.px=l.type==='water'?s.px+d[0]:nx;if(l.type!=='water')s.px=nx;s.py=ny;s.hop=1;
 const ci=l.coins.indexOf(nx);if(ci>=0){l.coins.splice(ci,1);s.coins++}
 if(ny>s.maxRow){s.maxRow=ny;s.idle=0;updateScore(ny)}}
function crossyEnd(reason){return finish(`${reason} ${score} lanes, ${state.coins} coin${state.coins===1?'':'s'}.`)}
function crossyUpdate(dt){const s=state;s.t+=dt;s.hop=Math.max(0,s.hop-dt*6);
 if(s.eagle){s.eagle.t+=dt;if(s.eagle.t>1.4)return crossyEnd('The eagle got Calum!');return}
 const follow=s.py-2;if(follow>s.cam)s.cam+=(follow-s.cam)*Math.min(1,dt*4);s.cam+=dt*(.1+s.t*.003);
 for(let r=Math.floor(s.cam)-1;r<s.cam+9;r++)crossyLane(r);for(const r in s.lanes)if(r<s.cam-2)delete s.lanes[r];
 for(const r in s.lanes){const l=s.lanes[r];
  if(l.type==='road')for(const c of l.cars){c.x+=l.dir*l.speed*dt;if(l.dir>0&&c.x>W+70)c.x-=W+220;if(l.dir<0&&c.x<-150)c.x+=W+220}
  if(l.type==='water')for(const g of l.logs){g.x+=l.dir*l.speed*dt;if(l.dir>0&&g.x>W+160)g.x-=W+360;if(l.dir<0&&g.x<-g.w-160)g.x+=W+360}
  if(l.type==='rail'){if(l.train){l.train.x+=l.dir*1500*dt;if((l.dir>0&&l.train.x>W+50)||(l.dir<0&&l.train.x+l.train.len<-50)){l.train=null;l.timer=3+Math.random()*4}}else{l.timer-=dt;if(l.timer<=0){const len=CT*9;l.train={len,x:l.dir>0?-len-40:W+40}}}}}
 s.idle+=dt;if(s.idle>9||s.py<s.cam-.5){s.eagle={t:0};return}
 const l=s.lanes[s.py],cx=s.px*CT+CT/2;
 if(l.type==='water'){const log=l.logs.find(g=>cx>g.x+8&&cx<g.x+g.w-8);if(!log)return crossyEnd('Splash! Calum can’t swim.');s.px+=l.dir*l.speed*dt/CT;if(s.px<-.4||s.px>CC-.6)return crossyEnd('Calum floated away.')}
 if(l.type==='road'&&l.cars.some(c=>cx+22>c.x+3&&cx-22<c.x+CT-3))return crossyEnd('Flattened by Frazer.');
 if(l.type==='rail'&&l.train&&cx+22>l.train.x&&cx-22<l.train.x+l.train.len)return crossyEnd('Hit by the train.')}
function crossyDraw(){const s=state,rowY=r=>H-(r-s.cam+1)*CT,lo=Math.floor(s.cam)-1,hi=Math.ceil(s.cam)+8;
 for(let r=lo;r<hi;r++){const l=crossyLane(r),y=rowY(r);
  if(l.type==='grass')rect(0,y,W,CT,r%2?'#5fb83c':'#57ad37');
  if(l.type==='road'){rect(0,y,W,CT,'#3b3f45');const up=s.lanes[r+1];if(up&&up.type==='road')for(let x=12;x<W;x+=80)rect(x,y-3,40,6,'#f1f0e8')}
  if(l.type==='water'){rect(0,y,W,CT,'#3aa0e8');for(let x=((s.t*30*l.dir)%90+90)%90-90;x<W;x+=90)rect(x,y+18+(Math.floor(x/90)%2)*30,40,4,'#8fd3ff')}
  if(l.type==='rail'){rect(0,y,W,CT,'#7a6a5c');for(let x=0;x<W;x+=30)rect(x+4,y+14,14,CT-28,'#5a4535');rect(0,y+22,W,6,'#c9ccd1');rect(0,y+CT-28,W,6,'#c9ccd1');const warn=!l.train&&l.timer<1.6;rect(8,y+6,8,CT-12,'#2b2b2b');circle(12,y+12,9,warn&&Math.floor(s.t*6)%2?'#ff2b2b':'#521414')}}
 for(let r=hi-1;r>=lo;r--){const l=s.lanes[r],y=rowY(r);if(!l)continue;
  if(l.type==='grass')for(const c of l.trees){const x=c*CT;rect(x+32,y+44,11,22,'#7a4e2a');circle(x+37,y+32,26,'#2f7a2a');circle(x+29,y+24,10,'#3f9a36')}
  if(l.type==='water')for(const g of l.logs){ctx.fillStyle='#8a5a33';ctx.beginPath();ctx.roundRect(g.x,y+10,g.w,CT-20,14);ctx.fill();for(let x=g.x+26;x<g.x+g.w-20;x+=50)rect(x,y+18,3,CT-36,'#6e4526');ctx.fillStyle='#b07a4c';ctx.beginPath();ctx.ellipse(g.x+g.w-10,y+CT/2,9,(CT-20)/2-2,0,0,Math.PI*2);ctx.fill()}
  for(const c of l.coins){const w=Math.abs(Math.sin(s.t*4+c))*14+3,x=c*CT+CT/2,cy=y+CT/2-4;ctx.fillStyle='#b8860b';ctx.beginPath();ctx.ellipse(x,cy+2,w,16,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffd23f';ctx.beginPath();ctx.ellipse(x,cy,w,16,0,0,Math.PI*2);ctx.fill()}
  if(l.type==='road')for(const c of l.cars){const cw=CT-4,ch=cw*16/9,cy=y+CT-ch-4;ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(c.x+cw/2,y+CT-4,cw/2+4,7,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.beginPath();ctx.roundRect(c.x,cy,cw,ch,7);ctx.clip();if(frazerCar.complete&&frazerCar.naturalWidth)ctx.drawImage(frazerCar,c.x,cy,cw,ch);else rect(c.x,cy,cw,ch,'#3057b8');ctx.restore();ctx.strokeStyle='#f1f0e8';ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(c.x,cy,cw,ch,7);ctx.stroke()}
  if(l.type==='rail'&&l.train){const t=l.train;for(let i=0;i<9;i++){const x=t.x+i*CT;ctx.fillStyle=i===(l.dir>0?8:0)?'#c62828':'#e53935';ctx.beginPath();ctx.roundRect(x+2,y-22,CT-4,CT+14,8);ctx.fill();rect(x+10,y-12,CT-20,18,'#bfe8f2');rect(x+2,y+CT-18,CT-4,8,'#8e1b1b')}}
  if(r===s.py&&!(s.eagle&&s.eagle.t>.6))crossyChicken(s.px*CT+CT/2,y+CT/2-Math.sin(s.hop*Math.PI)*16,true)}
 if(s.eagle){const e=s.eagle,px=s.px*CT+CT/2,py=rowY(s.py)+CT/2,down=Math.min(1,e.t/.6),ey=e.t<.6?-120+(py-40+120)*down:py-40-(e.t-.6)*700;if(e.t>.6)crossyChicken(px,ey+48,false);crossyEagle(px,ey,e.t)}
 rect(12,10,210,40,'#121310cc');text(`LANES ${score}`,24,38,20,'#f1f0e8','left');circle(160,30,11,'#ffd23f');text(`${s.coins}`,178,38,20,'#ffd23f','left')}
function crossyChicken(x,y,shadow){const r=28;if(shadow){ctx.fillStyle='#0004';ctx.beginPath();ctx.ellipse(x,y+r+10,22,7,0,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#f1f0e8';ctx.beginPath();ctx.ellipse(x-r-4,y+8,11,17,-.4,0,Math.PI*2);ctx.ellipse(x+r+4,y+8,11,17,.4,0,Math.PI*2);ctx.fill();circle(x-9,y-r-2,9,'#e8322c');circle(x,y-r-7,10,'#e8322c');circle(x+9,y-r-2,9,'#e8322c');drawPic(calumImg,x,y,r,'#f1f0e8');ctx.fillStyle='#ff9f1c';ctx.beginPath();ctx.moveTo(x-9,y+r-3);ctx.lineTo(x+9,y+r-3);ctx.lineTo(x,y+r+13);ctx.closePath();ctx.fill()}
function crossyEagle(x,y,t){const flap=Math.sin(t*22)*18;ctx.fillStyle='#4a2f1c';ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x-60,y-30-flap,x-110,y-8-flap);ctx.quadraticCurveTo(x-60,y+4,x,y+14);ctx.quadraticCurveTo(x+60,y+4,x+110,y-8-flap);ctx.quadraticCurveTo(x+60,y-30-flap,x,y);ctx.fill();ctx.fillStyle='#5b3a22';ctx.beginPath();ctx.ellipse(x,y+10,18,28,0,0,Math.PI*2);ctx.fill();circle(x,y-18,14,'#f1f0e8');ctx.fillStyle='#ffb300';ctx.beginPath();ctx.moveTo(x-5,y-12);ctx.lineTo(x+5,y-12);ctx.lineTo(x,y);ctx.closePath();ctx.fill();circle(x-5,y-21,2.5,'#121310');circle(x+5,y-21,2.5,'#121310');rect(x-12,y+34,5,12,'#ffb300');rect(x+7,y+34,5,12,'#ffb300')}
function drawPic(img,x,y,r,stroke){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();if(img.complete&&img.naturalWidth)ctx.drawImage(img,x-r,y-r,r*2,r*2);else rect(x-r,y-r,r*2,r*2,'#ff66c4');ctx.restore();ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke()}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}
function text(str,x,y,size=30,c='#f1f0e8',align='center'){ctx.fillStyle=c;ctx.font=`bold ${size}px 'Space Mono',monospace`;ctx.textAlign=align;ctx.fillText(str,x,y)}
function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
function drawFace(x,y,r){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();if(face.complete&&face.naturalWidth)ctx.drawImage(face,x-r,y-r,r*2,r*2);else rect(x-r,y-r,r*2,r*2,'#ff66c4');ctx.restore();ctx.strokeStyle='#b7ff39';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke()}
function draw(){rect(0,0,W,H,'#0d1512');ctx.strokeStyle='#233328';ctx.lineWidth=1;for(let x=0;x<W;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const s=state;
if(current.id==='slope'){rect(0,0,W,110,'#131121');text('NEON DISTRICT // ENDLESS DESCENT',450,55,14,'#ab93c7');ctx.fillStyle='#142b20';ctx.beginPath();ctx.moveTo(405,110);ctx.lineTo(495,110);ctx.lineTo(880,500);ctx.lineTo(20,500);ctx.closePath();ctx.fill();ctx.strokeStyle='#b7ff39';ctx.lineWidth=3;ctx.stroke();for(let i=0;i<14;i++){let z=(i/14+s.t*.45)%1;let y=110+z*z*390;ctx.beginPath();ctx.moveTo(450-(45+z*z*385),y);ctx.lineTo(450+(45+z*z*385),y);ctx.stroke()}for(const o of [...s.obstacles].sort((a,b)=>a.z-b.z)){const z=o.z;const w=12+z*z*55,x=450+o.x*(45+z*z*380),y=110+z*z*350;rect(x-w/2,y-w,w,w,'#ff4c87');rect(x-w/2+5,y-w+5,w-10,5,'#ffb0ce')}circle(450+s.x*350,443,24,'#b7ff39');circle(442+s.x*350,435,7,'#efffce');text('← KEEP IT ON THE GREEN →',450,485,13,'#b7ff39')}
if(current.id==='snake'){rect(0,0,W,10,'#b59aff');rect(0,490,W,10,'#b59aff');s.body.forEach((p,i)=>rect(p.x*30+2,p.y*30+12,26,26,i?'#7ec64f':'#b7ff39'));circle(s.food.x*30+15,s.food.y*30+25,11,'#ff66c4')}
if(current.id==='breakout'){s.bricks.forEach((b,i)=>{if(b.alive){rect(b.x,b.y,72,25,['#ff66c4','#b59aff','#ff9566','#b7ff39'][Math.floor(i/10)]);rect(b.x+4,b.y+4,64,3,'#ffffff66')}});rect(s.paddle-60,445,120,13,'#b7ff39');circle(s.x,s.y,9,'#f1f0e8');text(`BALLS ${s.lives}`,30,485,14,'#b7ff39','left')}
if(current.id==='flap'){for(const p of s.pipes){rect(p.x,0,65,p.gap-90,'#b7ff39');rect(p.x,p.gap+90,65,H-p.gap-90,'#b7ff39');rect(p.x-5,p.gap-104,75,14,'#7db327');rect(p.x-5,p.gap+90,75,14,'#7db327')}drawFace(180,s.y,23)}
if(current.id==='dodge'){s.rocks.forEach(r=>{ctx.strokeStyle='#ff956677';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x+20,r.y-50);ctx.stroke();circle(r.x,r.y,r.r,'#ff9566');circle(r.x-4,r.y-4,r.r*.35,'#ffcf93')});drawFace(s.x,445,23)}
if(current.id==='crossy')crossyDraw();
if(current.id==='reaction'){rect(0,0,W,H,s.green?'#b7ff39':'#673056');text(s.green?'TAP. RIGHT. NOW.':'WAIT FOR GREEN…',450,235,44,s.green?'#121310':'#f1f0e8');text(s.green?'SPACE / CLICK / ACTION':'NO EARLY STARTS.',450,285,18,s.green?'#121310':'#f1d8e9')}
}
renderCards();
const crossSpots=[[4,18,'#b7ff39'],[93,14,'#ff66c4'],[48,8,'#f1ed85'],[8,72,'#ff66c4'],[88,62,'#b7ff39'],[30,44,'#83dce9'],[70,86,'#b59aff'],[55,58,'#ff9566'],[20,92,'#f1ed85'],[78,36,'#83dce9']];
const crossLayer=document.createElement('div');crossLayer.className='crosses';
crossLayer.innerHTML=crossSpots.map(([x,y,c],i)=>`<a class="cross" href="/bible/" aria-label="Open the Bible" title="Open the Bible" style="left:${x}%;top:${y}%;--c:${c};--size:${22+(i%3)*8}px;--dur:${3+(i%4)*.7}s;--delay:${-i*.6}s"><svg viewBox="0 0 20 28" aria-hidden="true"><path fill="currentColor" d="M8 0h4v8h8v4h-8v16H8V12H0V8h8z"/></svg></a>`).join('');
document.body.appendChild(crossLayer);
