'use strict';
const $ = s => document.querySelector(s);
const games = [
 {id:'slope',name:'Neon Slope',art:'NEON<br>SLOPE',category:'Arcade',color:'#b7ff39',symbol:'◉',tag:'DOWNHILL CHAOS',desc:'Stay on the track. Dodge the blocks. Send it.',controls:'← → or A / D to steer. Touch: hold the arrow buttons.',note:'An original Slope-inspired mini-game, not the official Slope.'},
 {id:'snake',name:'Snake Syndicate',art:'SNAKE<br>SYNDICATE',category:'Classic',color:'#b59aff',symbol:'▟',tag:'CERTIFIED CLASSIC',desc:'Eat. Grow. Try not to eat yourself.',controls:'Arrow keys or W A S D to turn. Touch: use the direction buttons.'},
 {id:'breakout',name:'Brick Riot',art:'BRICK<br>RIOT',category:'Classic',color:'#ff9566',symbol:'▦',tag:'SMASH EVERYTHING',desc:'One paddle. One ball. Absolutely no mercy.',controls:'← → / A D or move the pointer to control the paddle.'},
 {id:'flap',name:'Flappy Lads',art:'FLAPPY<br>LADS',category:'Arcade',color:'#83dce9',symbol:'↗',tag:'JUST ONE MORE TRY',desc:'The lads have wings. This can only end well.',controls:'Space, ↑, tap the game or press ACTION to flap.'},
 {id:'dodge',name:'Meteor Meltdown',art:'METEOR<br>MELTDOWN',category:'Arcade',color:'#ff83c4',symbol:'✳',tag:'SURVIVAL MODE',desc:'Dodge the sky. Keep the streak alive.',controls:'← → / A D or move the pointer to dodge. Touch: hold arrows.'},
 {id:'reaction',name:'Reflex Check',art:'REFLEX<br>CHECK',category:'Quick',color:'#f1ed85',symbol:'ϟ',tag:'ARE YOU LOCKED IN?',desc:'Wait for green. Tap fast. Prove you’re awake.',controls:'Wait for green, then click the game or press Space / ACTION.',note:'Lower scores are better. Reaction time is measured in milliseconds.'}
];
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Private mode can disable storage. */}}
let favourites=read('bunker:favourites',[]);if(!Array.isArray(favourites))favourites=[];
let category='All';
function renderCards(){const query=$('#search').value.trim().toLowerCase();const list=games.filter(g=>(category==='All'||(category==='Favourites'?favourites.includes(g.id):g.category===category))&&`${g.name} ${g.desc} ${g.category}`.toLowerCase().includes(query));$('#game-grid').innerHTML=list.map((g,i)=>`<article class="game-card" style="--card-color:${g.color}"><button class="card-art" data-play="${g.id}" aria-label="Play ${g.name}"><span class="art-title">${g.art}</span><span class="art-symbol" aria-hidden="true">${g.symbol}</span><img class="art-photo" src="/images/${games.indexOf(g)%2?'el-classico':'hammock'}.jpeg" alt="" loading="lazy"><span class="card-badge">${g.tag}</span></button><button class="favourite" data-favourite="${g.id}" aria-label="Favourite ${g.name}" aria-pressed="${favourites.includes(g.id)}">${favourites.includes(g.id)?'♥':'♡'}</button><div class="card-body"><h3>${g.name}</h3><p>${g.desc}</p><div class="card-bottom"><span>${g.category.toUpperCase()} · FREE</span><button class="play" data-play="${g.id}">PLAY NOW ↗</button></div></div></article>`).join('');$('#result-count').textContent=`${list.length} GAMES. ZERO EXCUSES.`;$('#empty').hidden=!!list.length}
$('#search').addEventListener('input',renderCards);
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});renderCards()}));
$('#game-grid').addEventListener('click',e=>{const play=e.target.closest('[data-play]');if(play)openGame(play.dataset.play);const fav=e.target.closest('[data-favourite]');if(fav){const id=fav.dataset.favourite;favourites=favourites.includes(id)?favourites.filter(x=>x!==id):[...favourites,id];write('bunker:favourites',favourites);renderCards()}});
['#random-top','#random-hero','#random-bottom'].forEach(s=>$(s).addEventListener('click',()=>openGame(games[Math.floor(Math.random()*games.length)].id)));
const face=new Image();face.src='/images/hammock.jpeg';
const dialog=$('#player'),canvas=$('#canvas'),ctx=canvas.getContext('2d'),W=900,H=500;
let current=null,state=null,running=false,paused=false,score=0,best=0,frame=0,last=0,keys=new Set(),opener=null;
function bestKey(){return `bunker:best:${current.id}`}
function updateScore(n){score=Math.max(0,Math.floor(n));$('#score').textContent=current.id==='reaction'?`${score} ms`:score}
function setOverlay(title,msg,label){$('#overlay-title').textContent=title;$('#overlay-message').textContent=msg;$('#start').textContent=label;$('#overlay').hidden=false}
function openGame(id){opener=document.activeElement;current=games.find(g=>g.id===id);cancelAnimationFrame(frame);running=false;paused=false;keys.clear();$('#pause').textContent='PAUSE';$('#game-title').textContent=current.name;$('#instructions').textContent=current.controls;$('#game-note').textContent=current.note||'Original Bunker Box mini-game. Your best score stays on this device.';best=Number(read(bestKey(),0))||0;$('#best').textContent=best?`${best}${id==='reaction'?' ms':''}`:'—';updateScore(0);state=initialState(id);draw();setOverlay('READY TO SEND IT?',current.controls,'LET’S GO →');if(!dialog.open)dialog.showModal()}
function initialState(id){if(id==='slope')return {x:0,t:0,obstacles:[],spawn:0};if(id==='snake')return {body:[{x:10,y:10},{x:9,y:10},{x:8,y:10}],dx:1,dy:0,nextX:1,nextY:0,food:{x:20,y:10},tick:0};if(id==='breakout')return {paddle:450,x:450,y:365,vx:230,vy:-290,bricks:Array.from({length:40},(_,i)=>({x:42+(i%10)*82,y:45+Math.floor(i/10)*35,alive:true})),lives:3};if(id==='flap')return {y:230,vy:0,pipes:[],spawn:0};if(id==='dodge')return {x:450,t:0,rocks:[],spawn:0};return {wait:1.7+Math.random()*3,t:0,green:false,started:0}}
function start(){if(paused){paused=false;$('#pause').textContent='PAUSE';$('#overlay').hidden=true;last=performance.now();frame=requestAnimationFrame(loop);canvas.focus();return}state=initialState(current.id);updateScore(0);running=true;paused=false;keys.clear();$('#pause').textContent='PAUSE';$('#overlay').hidden=true;cancelAnimationFrame(frame);last=performance.now();frame=requestAnimationFrame(loop);canvas.focus()}
function finish(message,won=false){running=false;cancelAnimationFrame(frame);keys.clear();if(score>0&&(!best||(current.id==='reaction'?score<best:score>best))){best=score;write(bestKey(),best);$('#best').textContent=`${best}${current.id==='reaction'?' ms':''}`;message+=' New personal best!'}setOverlay(won?'ABSOLUTE SCENES.':'ONE MORE GO?',message,'PLAY AGAIN ↻')}
function togglePause(){if(!running)return;if(current.id==='reaction'){running=false;cancelAnimationFrame(frame);setOverlay('ROUND RESET','Reaction rounds restart when paused.','START AGAIN →');return}paused=!paused;keys.clear();$('#pause').textContent=paused?'RESUME':'PAUSE';if(paused){cancelAnimationFrame(frame);setOverlay('TAKE A BREATHER.','Your game is paused.','RESUME →')}else{$('#overlay').hidden=true;last=performance.now();frame=requestAnimationFrame(loop);canvas.focus()}}
function closeGame(){running=false;cancelAnimationFrame(frame);keys.clear();dialog.close();opener?.focus()}
$('#close').addEventListener('click',closeGame);dialog.addEventListener('cancel',e=>{e.preventDefault();closeGame()});dialog.addEventListener('close',()=>{running=false;cancelAnimationFrame(frame);keys.clear()});$('#start').addEventListener('click',start);$('#restart').addEventListener('click',()=>{paused=false;start()});$('#pause').addEventListener('click',togglePause);
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(dialog.requestFullscreen)await dialog.requestFullscreen();else $('#game-note').textContent='Fullscreen is not available in this browser. Rotate your phone for a wider view.'}catch{$('#game-note').textContent='Fullscreen is not available in this browser.'}});
function action(key){if(!running||paused)return;if(current.id==='snake'){const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[key];if(d&&(d[0]!==-state.dx||d[1]!==-state.dy)){state.nextX=d[0];state.nextY=d[1]}}if(current.id==='flap'&&(key==='Space'||key==='ArrowUp'))state.vy=-320;if(current.id==='reaction'&&key==='Space'){if(!state.green){updateScore(0);finish('Too early! Wait until the screen turns green.')}else{updateScore(performance.now()-state.started);finish(`${score} ms. That’s your reaction time.`,true)}}}
function normalize(e){return {KeyA:'ArrowLeft',KeyD:'ArrowRight',KeyW:'ArrowUp',KeyS:'ArrowDown'}[e.code]||e.code}
document.addEventListener('keydown',e=>{if(!dialog.open){if(e.key==='/'&&e.target.tagName!=='INPUT'){e.preventDefault();$('#search').focus()}return}const key=normalize(e);if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(key)&&e.target===canvas){e.preventDefault();keys.add(key);if(!e.repeat)action(key)}if(e.code==='KeyP'&&e.target===canvas)togglePause()});document.addEventListener('keyup',e=>keys.delete(normalize(e)));
window.addEventListener('blur',()=>{keys.clear();if(running&&!paused)togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)togglePause()});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);action(b.dataset.key)});['pointerup','pointercancel','lostpointercapture'].forEach(type=>b.addEventListener(type,()=>keys.delete(b.dataset.key)))});
canvas.addEventListener('pointerdown',e=>{canvas.focus();action('Space');movePointer(e)});canvas.addEventListener('pointermove',movePointer);
function movePointer(e){if(!running||paused)return;const x=(e.clientX-canvas.getBoundingClientRect().left)/canvas.getBoundingClientRect().width*W;if(current.id==='breakout')state.paddle=Math.max(60,Math.min(W-60,x));if(current.id==='dodge')state.x=Math.max(22,Math.min(W-22,x))}
function loop(now){if(!running||paused)return;const dt=Math.min((now-last)/1000,.04);last=now;update(dt);draw();if(running)frame=requestAnimationFrame(loop)}
function update(dt){const steer=(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0);const s=state;
if(current.id==='slope'){s.t+=dt;s.x+=steer*dt*1.6;s.spawn-=dt;const speed=1+s.t*.012;if(s.spawn<=0){s.obstacles.push({x:(Math.random()-.5)*1.4,z:0});s.spawn=.7+Math.random()*.6}for(const o of s.obstacles)o.z+=dt*.43*speed;s.obstacles=s.obstacles.filter(o=>o.z<1.1);updateScore(s.t*10);if(Math.abs(s.x)>.93)return finish('You fell off the track. Steer a little earlier!');if(s.obstacles.some(o=>o.z>.88&&o.z<1.04&&Math.abs(o.x-s.x)<.18))return finish(`Block collision. You made it ${score} metres.`)}
if(current.id==='snake'){s.tick+=dt;if(s.tick>=Math.max(.075,.15-score*.002)){s.tick=0;s.dx=s.nextX;s.dy=s.nextY;const head={x:s.body[0].x+s.dx,y:s.body[0].y+s.dy};const eating=head.x===s.food.x&&head.y===s.food.y;const body=eating?s.body:s.body.slice(0,-1);if(head.x<0||head.x>=30||head.y<0||head.y>=16||body.some(p=>p.x===head.x&&p.y===head.y))return finish(`Snake stopped. ${score} snacks collected.`);s.body.unshift(head);if(eating){updateScore(score+1);const free=[];for(let y=0;y<16;y++)for(let x=0;x<30;x++)if(!s.body.some(p=>p.x===x&&p.y===y))free.push({x,y});if(!free.length)return finish('You filled the board!',true);s.food=free[Math.floor(Math.random()*free.length)]}else s.body.pop()}}
if(current.id==='breakout'){s.paddle=Math.max(60,Math.min(W-60,s.paddle+steer*dt*620));const prevY=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.x<10||s.x>W-10){s.vx*=-1;s.x=Math.max(10,Math.min(W-10,s.x))}if(s.y<10){s.vy=Math.abs(s.vy);s.y=10}if(s.vy>0&&prevY<=435&&s.y>=435&&Math.abs(s.x-s.paddle)<70){s.y=435;s.vy=-Math.abs(s.vy);s.vx=(s.x-s.paddle)*6}for(const b of s.bricks){if(b.alive&&s.x>b.x-8&&s.x<b.x+80&&s.y>b.y-8&&s.y<b.y+32){b.alive=false;s.vy*=-1;updateScore(score+10);break}}if(s.y>H+10){s.lives--;if(!s.lives)return finish(`Out of balls. ${score} points of brick destruction.`);s.x=s.paddle;s.y=365;s.vx=230;s.vy=-290}if(s.bricks.every(b=>!b.alive))return finish('All bricks cleared. Total demolition.',true)}
if(current.id==='flap'){s.vy+=dt*850;s.y+=s.vy*dt;s.spawn-=dt;if(s.spawn<=0){s.pipes.push({x:W+30,gap:130+Math.random()*240,passed:false});s.spawn=1.8}for(const p of s.pipes){p.x-=dt*220;if(p.x+65<180&&!p.passed){p.passed=true;updateScore(score+1)}if(p.x<205&&p.x+65>155&&(s.y-21<p.gap-90||s.y+21>p.gap+90))return finish(`${score} gates cleared. The lads will fly again.`)}s.pipes=s.pipes.filter(p=>p.x>-80);if(s.y<22||s.y>H-22)return finish('Gravity wins this round.')}
if(current.id==='dodge'){s.t+=dt;s.x=Math.max(22,Math.min(W-22,s.x+steer*dt*500));s.spawn-=dt;if(s.spawn<=0){s.rocks.push({x:25+Math.random()*850,y:-40,r:15+Math.random()*15,speed:170+Math.random()*130+s.t*5});s.spawn=Math.max(.16,.55-s.t*.006)}for(const r of s.rocks){r.y+=dt*r.speed;if(Math.hypot(r.x-s.x,r.y-445)<r.r+18)return finish(`You survived ${score} seconds of meteor madness.`)}s.rocks=s.rocks.filter(r=>r.y<550);updateScore(s.t)}
if(current.id==='reaction'){s.t+=dt;if(!s.green&&s.t>=s.wait){s.green=true;s.started=performance.now()}}
}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}
function text(str,x,y,size=30,c='#f1f0e8',align='center'){ctx.fillStyle=c;ctx.font=`bold ${size}px 'Space Mono',monospace`;ctx.textAlign=align;ctx.fillText(str,x,y)}
function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
function drawFace(x,y,r){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();if(face.complete&&face.naturalWidth)ctx.drawImage(face,x-r,y-r,r*2,r*2);else rect(x-r,y-r,r*2,r*2,'#ff66c4');ctx.restore();ctx.strokeStyle='#b7ff39';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke()}
function draw(){rect(0,0,W,H,'#0d1512');ctx.strokeStyle='#233328';ctx.lineWidth=1;for(let x=0;x<W;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const s=state;
if(current.id==='slope'){rect(0,0,W,110,'#131121');text('NEON DISTRICT // ENDLESS DESCENT',450,55,14,'#ab93c7');ctx.fillStyle='#142b20';ctx.beginPath();ctx.moveTo(405,110);ctx.lineTo(495,110);ctx.lineTo(880,500);ctx.lineTo(20,500);ctx.closePath();ctx.fill();ctx.strokeStyle='#b7ff39';ctx.lineWidth=3;ctx.stroke();for(let i=0;i<14;i++){let z=(i/14+s.t*.45)%1;let y=110+z*z*390;ctx.beginPath();ctx.moveTo(450-(45+z*z*385),y);ctx.lineTo(450+(45+z*z*385),y);ctx.stroke()}for(const o of [...s.obstacles].sort((a,b)=>a.z-b.z)){const z=o.z;const w=12+z*z*55,x=450+o.x*(45+z*z*380),y=110+z*z*350;rect(x-w/2,y-w,w,w,'#ff4c87');rect(x-w/2+5,y-w+5,w-10,5,'#ffb0ce')}circle(450+s.x*350,443,24,'#b7ff39');circle(442+s.x*350,435,7,'#efffce');text('← KEEP IT ON THE GREEN →',450,485,13,'#b7ff39')}
if(current.id==='snake'){rect(0,0,W,10,'#b59aff');rect(0,490,W,10,'#b59aff');s.body.forEach((p,i)=>rect(p.x*30+2,p.y*30+12,26,26,i?'#7ec64f':'#b7ff39'));circle(s.food.x*30+15,s.food.y*30+25,11,'#ff66c4')}
if(current.id==='breakout'){s.bricks.forEach((b,i)=>{if(b.alive){rect(b.x,b.y,72,25,['#ff66c4','#b59aff','#ff9566','#b7ff39'][Math.floor(i/10)]);rect(b.x+4,b.y+4,64,3,'#ffffff66')}});rect(s.paddle-60,445,120,13,'#b7ff39');circle(s.x,s.y,9,'#f1f0e8');text(`BALLS ${s.lives}`,30,485,14,'#b7ff39','left')}
if(current.id==='flap'){for(const p of s.pipes){rect(p.x,0,65,p.gap-90,'#b7ff39');rect(p.x,p.gap+90,65,H-p.gap-90,'#b7ff39');rect(p.x-5,p.gap-104,75,14,'#7db327');rect(p.x-5,p.gap+90,75,14,'#7db327')}drawFace(180,s.y,23)}
if(current.id==='dodge'){s.rocks.forEach(r=>{ctx.strokeStyle='#ff956677';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x+20,r.y-50);ctx.stroke();circle(r.x,r.y,r.r,'#ff9566');circle(r.x-4,r.y-4,r.r*.35,'#ffcf93')});drawFace(s.x,445,23)}
if(current.id==='reaction'){rect(0,0,W,H,s.green?'#b7ff39':'#673056');text(s.green?'TAP. RIGHT. NOW.':'WAIT FOR GREEN…',450,235,44,s.green?'#121310':'#f1f0e8');text(s.green?'SPACE / CLICK / ACTION':'NO EARLY STARTS.',450,285,18,s.green?'#121310':'#f1d8e9')}
}
renderCards();
