import test from 'node:test';
import assert from 'node:assert/strict';
import {SEPOLIA,parseTestEth,creditsFromWei,sendDeposit,verifyDeposit} from '../wallet.js';
const from='0x'+'1'.repeat(40),to='0x'+'2'.repeat(40),hash='0x'+'3'.repeat(64),blockHash='0x'+'4'.repeat(64);
const pending={from,to,hash,wei:'1000000000000000',chainId:SEPOLIA};
function mock(overrides={}){const calls=[];return {calls,async request({method,params}){calls.push({method,params});if(method in overrides)return typeof overrides[method]==='function'?overrides[method](params):overrides[method];return {eth_chainId:SEPOLIA,eth_accounts:[from],eth_sendTransaction:hash,eth_getTransactionReceipt:{status:'0x1',transactionHash:hash,blockNumber:'0xa',blockHash},eth_getTransactionByHash:{hash,from,to,value:'0x38d7ea4c68000',chainId:SEPOLIA},eth_getBlockByNumber:{hash:blockHash},eth_blockNumber:'0xb'}[method];}};}
test('test ETH conversion is exact and bounded',()=>{assert.equal(parseTestEth('0.001'),10n**15n);assert.equal(creditsFromWei(10n**15n),10000);for(const x of ['0','0.100000000000000001','1e-3','-1','1.0000000000000000001'])assert.throws(()=>parseTestEth(x));});
test('unconfigured deposit cannot request a transaction',async()=>{const p=mock();await assert.rejects(sendDeposit(p,'','0.001'));assert.equal(p.calls.length,0);});
test('mainnet is refused before a transaction request',async()=>{const p=mock({eth_chainId:'0x1'});await assert.rejects(sendDeposit(p,to,'0.001'),/Sepolia/);assert.equal(p.calls.some(c=>c.method==='eth_sendTransaction'),false);});
test('network change before signing is caught by the second chain check',async()=>{let n=0;const p=mock({eth_chainId:()=>++n===1?SEPOLIA:'0x1'});await assert.rejects(sendDeposit(p,to,'0.001'));assert.equal(p.calls.some(c=>c.method==='eth_sendTransaction'),false);});
test('transaction contains the exact amount, recipient and Sepolia chain',async()=>{const p=mock();assert.deepEqual(await sendDeposit(p,to,'0.001'),pending);const tx=p.calls.find(c=>c.method==='eth_sendTransaction').params[0];assert.equal(tx.to,to);assert.equal(tx.chainId,SEPOLIA);assert.equal(BigInt(tx.value),10n**15n);});
test('pending and insufficiently confirmed transactions are not credited',async()=>{assert.equal((await verifyDeposit(mock({eth_getTransactionReceipt:null}),pending)).state,'pending');assert.equal((await verifyDeposit(mock({eth_blockNumber:'0xa'}),pending)).state,'pending');});
test('failed transaction and mismatched recipient are rejected',async()=>{await assert.rejects(verifyDeposit(mock({eth_getTransactionReceipt:{status:'0x0'}}),pending));await assert.rejects(verifyDeposit(mock({eth_getTransactionByHash:{hash,from,to:from,value:'0x38d7ea4c68000',chainId:SEPOLIA}}),pending));});
test('block reorganisation returns pending, not confirmed',async()=>{assert.equal((await verifyDeposit(mock({eth_getBlockByNumber:{hash:'0x'+'5'.repeat(64)}}),pending)).state,'pending');});
test('only fully matching Sepolia transaction with two confirmations succeeds',async()=>{const result=await verifyDeposit(mock(),pending);assert.equal(result.state,'confirmed');assert.equal(result.confirmations,2);assert.equal(result.wei,pending.wei);});
